// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"GinTest1/api/controller"
	"GinTest1/usecase"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeController(logger *zap.Logger, router *gin.RouterGroup) *controller.TestController {
	testUsecase := usecase.NewTestUseCase()
	testController := controller.NewTestController(testUsecase, logger, router)
	return testController
}
