name: GitHub Actions Demo
run-name: CD 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: wsl-ubuntu
    steps:
      - name: Get Workflow Run ID
        run: echo "Workflow Run ID ${{ github.run_id }}"
      - name: Get Workflow Run number
        run: echo "Workflow Run ID ${{ github.run_number }}"
