name: GitHub Actions CD
run-name: CD Flow 🚀
on: [push]
jobs:
  build:
    name: Build image and push
    runs-on: wsl-ubuntu
    steps:      
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: chmod +x build.sh
      - run: ./build.sh ${{ github.run_id }}
  deploy:
    name: Pull image and deploy
    runs-on: wsl-ubuntu
    steps:      
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: chmod +x run.sh
      - run: ./run.sh ${{ github.run_id }}
