name: GitHub Actions CD
run-name: CD Flow 🚀
on: [push]
jobs:
  build:
    name: Build image and push
    runs-on: wsl-ubuntu
    steps:
      - run: chmod +x build.sh
      - run: ./build.sh ${{ github.run_id }}
